# Site settings
title: Antidote
email: mychembl@ebi.ac.uk
url: http://chembl.github.io/antidote/
description: ""
skills: "An open platform for data-driven drug discovery applications"
meta_author: Michal Nowotka

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: DAE3E1 #A2122F

# Footer settings
footer:
  copyright: ChEMBL Group EMBL-EBI
  location: Cambridge, UK
  social: Our team
  credits: Credits

#social
twitter_username: ChEMBL
github_username: chembl

# Postal address (add as many lines as necessary)
address:
  - line: Wellcome Trust Genome Campus, Hinxton
  - line: Cambridgeshire, CB10 1SD, UK

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
